dataset:
  division_test_size: 0.2
  division_random_state: 42
  division_stratify: true
  selected: sephora # sephora, rotten_tomatoes

preprocessing:
  columns: all # all, text, numeric
  dim_reduction: umap # none, pca, umap
  dim_reduction_n: 3
  vectorization: bow # bow, tf-idf, word2vec

training:
  use_cross_validation: false
  use_grid_search: false

analysis:
  create_shap_graph: false

model:
  selected: svm # dummy, svm, random_forest
  dummy:
    strategy: uniform
    random_state: 42
  svm:
    kernel: linear
    gamma: scale
    tol: 0.01
  random_forest:
    n_estimators: 25
    min_samples_split: 0.3
    min_samples_leaf: 0.1
    max_features: 0.1
    max_depth: 100

grid_search:
  engine: RandomSearch # RandomSearch, GridSearch, HalvingRandomSearch, HalvingGridSearch

  param_grid:
    svm:
      kernel:
      - linear
      - poly
      - rbf
      - sigmoid
      gamma:
      - scale
      - auto
      tol:
      - 0.01
      - 0.001
      - 0.0001
    random_forest:
      n_estimators:
      - 5
      - 10
      - 25
      - 50
      min_samples_split:
      - 0.1
      - 0.2
      - 0.3
      - 0.4
      - 0.5
      min_samples_leaf:
      - 0.1
      - 0.2
      - 0.3
      - 0.4
      - 0.5
      max_features:
      - 0.1
      - 0.2
      - 0.3
      - 0.4
      - 0.5
      max_depth:
      - 
      - 5
      - 25
      - 100
